# Criado por: André Rocha 18/02/2025

name: Projeto_modulo_4

services:

  # Imagem criada por mim presente no docker hub
  python:
    image: andr3roch4/ea:v1
    container_name: python_app

  # Jellyfin server
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    volumes:
      - /home/andre:/config
      - /home/andre:/cache
      - type: bind
        source: /home/andre
        target: /media
      - type: bind
        source: /home/andre
        target: /media2
        read_only: true
    restart: 'unless-stopped'
    ports:
      - 8096:8096
  
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    restart: unless-stopped

  # Serviços de container monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped
    privileged: true
    networks:
      - container_net
    depends_on:
      - cadvisor
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    privileged: true
    networks:
      - container_net
    depends_on:
      - jellyfin
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    privileged: true
    networks:
      - container_net
    depends_on:
      - prometheus

networks:
  container_net:
    driver: bridge
    